export const cryptoList = [
  {
    rank: 1,
    name: 'Bitcoin',
    symbol: 'BTC',
    price_usd: 87873.8,
    changeIn24h: 3.4,
  },
  {
    rank: 2,
    name: 'Ethereum',
    symbol: 'ETH',
    price_usd: 2085.15,
    changeIn24h: 4.6,
  },
  {
    rank: 3,
    name: 'XRP',
    symbol: 'XRP',
    price_usd: 2.54,
    changeIn24h: 11.19,
  },
  {
    rank: 4,
    name: 'Tether',
    symbol: 'USDT',
    price_usd: 1.0,
    changeIn24h: 0.05,
  },
  {
    rank: 5,
    name: 'Binance Coin',
    symbol: 'BNB',
    price_usd: 617.76,
    changeIn24h: -2.03,
  },
  {
    rank: 6,
    name: 'Solana',
    symbol: 'SOL',
    price_usd: 134.52,
    changeIn24h: 7.65,
  },
  {
    rank: 7,
    name: 'Toncoin',
    symbol: 'TON',
    price_usd: 3.68,
    changeIn24h: 0.8,
  },
  {
    rank: 8,
    name: 'LEO Token',
    symbol: 'LEO',
    price_usd: 9.77,
    changeIn24h: 0.0,
  },
  {
    rank: 9,
    name: 'Wrapped stETH',
    symbol: 'WSTETH',
    price_usd: 2504.18,
    changeIn24h: 4.9,
  },
  {
    rank: 10,
    name: 'Stellar',
    symbol: 'XLM',
    price_usd: 0.2897,
    changeIn24h: 3.1,
  },
];
