events {}

http {

    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cache_zone:10m max_size=100m inactive=60m use_temp_path=off;

    resolver 8.8.8.8 8.8.4.4 valid=300s ipv4=on;
    proxy_ssl_protocols TLSv1.2 TLSv1.3;
    proxy_ssl_ciphers HIGH:!aNULL:!MD5:!RC4:!DES:!3DES:!DSS:!PSK:!SRP:!CAMELLIA;
    proxy_ssl_server_name on;

    server {
        listen 3000;
        server_name localhost;

        location / {
            proxy_pass https://api.coingecko.com;

            proxy_cache cache_zone;
            proxy_cache_valid 200 10m;
            proxy_cache_valid 404 1m;
            add_header X-Proxy-Cache $upstream_cache_status;

            proxy_set_header Host api.coingecko.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}